### ISSUE TITLE
Rename "Paris 1.5C" scenario to "Accelerated Actions" scenario.

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#145]

**Comment by holak** [comment]
What do you think the best way to do scenario names is? My excel file names can mimic the scenario name we want but with _ instead of spaces (e.g. "Accelerated_Actions") and you could then have code that replaces "_" with spaces. Or I could add a tab to the excel that has the scenario name that we would like to display. What do you think?

**Comment by cypressf** [comment]
Let's use the file name with underscores
