### ISSUE TITLE
change graph style for percentile — thicker median

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#168]

**Comment by cypressf** [comment]
![Screen Shot 2021-04-29 at 16 05 08](https://user-images.githubusercontent.com/443397/116611693-acdc1580-a904-11eb-9df7-e6ec2368552d.png)

I might consider using [`geom_ribbon`](https://ggplot2.tidyverse.org/reference/geom_ribbon.html?q=geom%20_%20ribbon) to make a filled-in range of color for the percentile ranges.

**Comment by holak** [comment]
@cypressf  that would be great. The figures in the Outlook Report look something like this:
![image](https://user-images.githubusercontent.com/12715920/116615040-bbc4c700-a908-11eb-8f04-df691be491c9.png)
 With the thick line representing the median, the dashed lines the interquartile range (25th-75th percentiles) and the shaded area the 5th-95th percentiles)

**Comment by cypressf** [comment]
How's this look?

![Screen Shot 2021-04-29 at 19 10 50](https://user-images.githubusercontent.com/443397/116629162-a3f83d80-a91e-11eb-8033-9ccc6263dea2.png)

**Comment by holak** [comment]
Awesome!!

**Comment by cypressf** [comment]
Is it mathematically sound to say that the values in the 25th to 75th percentile have a 50% likelihood and the values from the 5th to 95th percentile have a 90% likelihood? I wanted to add a legend like so:

<img width="786" alt="Screen Shot 2021-04-30 at 00 01 58" src="https://user-images.githubusercontent.com/443397/116646911-49270c00-a947-11eb-8cde-d555d5c49994.png">

**Comment by cypressf** [comment]
Maybe "Confidence Interval" is the term I'm looking for, not "Likelihood"

**Comment by cypressf** [comment]
I'll close this, and if confidence interval is not the correct term, lmk and I can change the legend title.

<img width="797" alt="Screen Shot 2021-04-30 at 01 07 01" src="https://user-images.githubusercontent.com/443397/116651121-66aca380-a950-11eb-8449-13da92de89a5.png">

**Comment by holak** [comment]
@cypressf "Confidence Interval" works, but is it too technical for general audiences? Other potential options: "Probability Range", "Probability Bounds", even "Likelihood" which less technically precise could work. Let's ask Sergey and Adam for their thoughts as well. Also would it be too long for the labels to be: "90% (5th-95th percentile)", "50% (25th-75th percentile)"? Maybe that's too much and not necessary? Finally, is there a way to also have a label for the black line as the median? I guess that gets tricky because median wouldn't fall under the same label heading as the probability bounds... maybe a reason to go with the more general "Likelihood"? Let's give it some more thought and circle back. I really like the shaded areas though.

**Comment by holak** [comment]
@cypressf the consensus was to change the legend title from "Confidence Interval" to "Likelihood Range"

**Comment by cypressf** [comment]
Cool. I'll rename it!
